services:
  change-vol-ownership:
    image: alpine
    volumes:
      - ./data-dev-sqlite/wallet:/mnt/wallet
    command: "chown -R 1000: /mnt/wallet"

  monero-wallet-rpc:
    image: ghcr.io/sethforprivacy/simple-monero-wallet-rpc:v0.18.3.4
    command: --wallet-dir wallet --disable-rpc-login --rpc-bind-port=28081 --daemon-host=${MONERO_DAEMON_RPC_HOSTNAME} --daemon-port=${MONERO_DAEMON_RPC_PORT}
    volumes:
      - ./data-dev-sqlite/wallet:/home/monero/wallet
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail localhost:28081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_version"}'
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  moneropay:
    build: .
    volumes:
      - ./data-dev-sqlite/sqlite:/app/sqlite
    environment:
      - RPC_ADDRESS=http://monero-wallet-rpc:28081/json_rpc
      - ZERO_CONF=true
      - SQLITE=file:/app/sqlite/db.sqlite
    depends_on:
      monero-wallet-rpc:
        condition: service_healthy
    restart: unless-stopped
