services:
  change-vol-ownership:
    image: alpine
    volumes:
      - ./data-dev-postgresql/wallet:/mnt/wallet
    command: "chown -R 1000: /mnt/wallet"

  monero-wallet-rpc:
    image: ghcr.io/sethforprivacy/simple-monero-wallet-rpc:v0.18.3.4
    command: --wallet-dir wallet --disable-rpc-login --rpc-bind-port=28081 --daemon-host=${MONERO_DAEMON_RPC_HOSTNAME} --daemon-port=${MONERO_DAEMON_RPC_PORT}
    volumes:
      - ./data-dev-postgresql/wallet:/home/monero/wallet
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail localhost:28081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_version"}'
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  postgresql:
    image: postgres:17-alpine
    volumes:
      - ./data-dev-postgresql/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD
      - POSTGRES_DB=${POSTGRES_DATABASE}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USERNAME}
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  moneropay:
    build: .
    environment:
      - RPC_ADDRESS=http://monero-wallet-rpc:28081/json_rpc
      - POSTGRESQL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DATABASE}?sslmode=disable
      - ZERO_CONF=true
    depends_on:
      monero-wallet-rpc:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    restart: unless-stopped

  # http://127.0.0.1:5001/?pgsql=postgresql&username=moneropay&db=moneropay
  adminer:
    image: dockette/adminer:dg
    ports:
      - 127.0.0.1:5001:80
    depends_on:
      postgresql:
        condition: service_healthy
    restart: unless-stopped