services:
  monero-wallet-rpc:
    image: ghcr.io/sethforprivacy/simple-monero-wallet-rpc:v0.18.3.3
    command: --wallet-file wallet --password-file wallet.passwd --disable-rpc-login --rpc-bind-port=28081 --daemon-host=${MONERO_DAEMON_RPC_HOSTNAME} --daemon-port=${MONERO_DAEMON_RPC_PORT}
    volumes:
      - ./data/wallet:/home/monero/wallet
    restart: unless-stopped

  postgresql:
    image: postgres:14-alpine
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: unless-stopped

  moneropay:
    image: registry.gitlab.com/moneropay/moneropay:v2
    # volumes:
    #  - ./data/sqlite:/app/sqlite
    environment:
      - RPC_ADDRESS=http://monero-wallet-rpc:28081/json_rpc
      - POSTGRESQL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DATABASE}?sslmode=disable
      - ZERO_CONF=false # set true to enable 0-conf
      # - SQLITE=file:/app/sqlite/db.sqlite
    depends_on:
      - monero-wallet-rpc
      - postgresql
    restart: unless-stopped
