#!/usr/bin/env python3
"""Generate Go wordlist files from Monero C++ mnemonic headers."""

import re
import sys
from pathlib import Path

GPL_HEADER = """\
/*
 * MoneroPay is a Monero payment processor.
 * Copyright (C) 2026 Laurynas Četyrkinas <laurynas@digilol.net>
 *
 * MoneroPay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MoneroPay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MoneroPay.  If not, see <https://www.gnu.org/licenses/>.
 */
"""


def parse_header(path: Path) -> tuple[list[str], str, str, int] | None:
    """Parse language header. Returns (words, native_name, english_name, prefix) or None."""
    content = path.read_text(encoding="utf-8")
    words_match = re.search(r'words\[NWORDS\]\s*=\s*\{([^}]+)\};', content, re.DOTALL)
    base_match = re.search(r'Base\("([^"]+)",\s*"([^"]+)",\s*\{\},\s*(\d+)\)', content)
    if not words_match or not base_match:
        return None
    words = [w.lower() for w in re.findall(r'"([^"]+)"', words_match.group(1))]
    return words, base_match.group(1), base_match.group(2), int(base_match.group(3))


def to_varname(filename: str) -> str:
    return "".join(w.capitalize() for w in filename.removesuffix(".h").split("_"))


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <monero_source_dir> <version>", file=sys.stderr)
        return 1

    mnemonics_dir = Path(sys.argv[1]) / "src" / "mnemonics"
    version, output_dir = sys.argv[2], Path(__file__).parent

    if not mnemonics_dir.is_dir():
        print(f"Error: {mnemonics_dir} not found", file=sys.stderr)
        return 1

    languages = []
    for path in sorted(mnemonics_dir.glob("*.h")):
        if (result := parse_header(path)) is None:
            continue
        words, native, english, prefix = result
        varname = to_varname(path.name)

        lines = [
            GPL_HEADER,
            "// Code generated by generate_wordlists.py from Monero source. DO NOT EDIT.",
            f"// Source: https://github.com/monero-project/monero/blob/{version}/src/mnemonics/{path.name}",
            "",
            "package xmrkey",
            "",
            f"// {varname}Wordlist is the Monero {varname} mnemonic wordlist.",
            f"var {varname}Wordlist = []string{{",
            *(f'\t"{w}",' for w in words),
            "}",
            "",
        ]
        (output_dir / f"wordlist_{varname.lower()}.go").write_text("\n".join(lines))
        languages.append((varname, prefix, native, english))

    lines = [
        GPL_HEADER,
        "// Code generated by generate_wordlists.py. DO NOT EDIT.",
        "",
        "package xmrkey",
        "",
        "// Language represents a mnemonic language with its wordlist and configuration.",
        "type Language struct {",
        "\tName        string   // Native name of the language",
        "\tEnglishName string   // English name of the language",
        "\tPrefixLen   int      // Unique prefix length for checksum calculation",
        "\tWords       []string // The 1626 words in the wordlist",
        "}",
        "",
        "// Languages contains all available mnemonic languages.",
        "var Languages = map[string]*Language{",
    ]
    for varname, prefix, native, english in sorted(languages):
        lines += [
            f'\t"{varname.lower()}": {{',
            f'\t\tName:        "{native}",',
            f'\t\tEnglishName: "{english}",',
            f'\t\tPrefixLen:   {prefix},',
            f'\t\tWords:       {varname}Wordlist,',
            "\t},",
        ]
    lines += ["}", ""]
    (output_dir / "wordlist_languages.go").write_text("\n".join(lines))

    return 0


if __name__ == "__main__":
    sys.exit(main())
