/*
 * MoneroPay is a Monero payment processor.
 * Copyright (C) 2026 Laurynas Četyrkinas <laurynas@digilol.net>
 *
 * MoneroPay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MoneroPay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MoneroPay.  If not, see <https://www.gnu.org/licenses/>.
 */

package xmrkey

import (
	"encoding/hex"
	"errors"
	"strings"
	"testing"
)

// Test vectors generated using monero-wallet-cli v0.18.4.5
// Each mnemonic was generated by wallet-cli and verified against the spend key.

func TestMnemonicVectors(t *testing.T) {
	tests := []struct {
		name     string
		mnemonic string
		keyHex   string
	}{
		{
			name:     "mainnet",
			mnemonic: "skater fountain lair oars delayed lopped pause duckling lumber exit jingle until dolphin ought ramped makeup adept joking optical abrasive ability puddle popular rockets makeup",
			keyHex:   "83aaa12a23059f50c63e1a4b11589675aef480122951a66f7eeeaaffba16060e",
		},
		{
			name:     "testnet",
			mnemonic: "factual rage vibrate psychic maps mighty phone joyous duke sensible fifteen psychic ringing rally tarnished tiers atrium elope toxic answers eternal kisses eternal ferry vibrate",
			keyHex:   "59cfae3d4d6a99038b7844c5d61b5d6350077423f013512c19232f37669dcc05",
		},
		{
			name:     "stagenet",
			mnemonic: "anvil fudge syndrome luggage reruns syllabus lava memoir weird fungal maverick thumbs aplomb gourmet equip upgrade jabbed mirror pairing desk injury dawn tinted uptight anvil",
			keyHex:   "9710f183e594b61c93bdca6ea485de53a794cde8d955df1a7ab0d138b102c30e",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Test MnemonicToKey
			key, lang, err := MnemonicToKey(tt.mnemonic)
			if err != nil {
				t.Fatalf("MnemonicToKey() failed: %v", err)
			}
			if hex.EncodeToString(key[:]) != tt.keyHex {
				t.Errorf("MnemonicToKey() = %s, want %s", hex.EncodeToString(key[:]), tt.keyHex)
			}
			if lang != "english" {
				t.Errorf("MnemonicToKey() language = %s, want english", lang)
			}

			// Test KeyToMnemonic
			keyBytes, _ := hex.DecodeString(tt.keyHex)
			var keyArr [32]byte
			copy(keyArr[:], keyBytes)
			mnemonic, err := KeyToMnemonic(keyArr, "english")
			if err != nil {
				t.Fatalf("KeyToMnemonic() failed: %v", err)
			}
			if mnemonic != tt.mnemonic {
				t.Errorf("KeyToMnemonic() = %s, want %s", mnemonic, tt.mnemonic)
			}
		})
	}
}

func TestMnemonicRoundtrip(t *testing.T) {
	// Generate a key and verify mnemonic roundtrip
	key, err := NewKey(NetworkMainnet)
	if err != nil {
		t.Fatalf("NewKey() failed: %v", err)
	}

	mnemonic, err := key.Mnemonic("english")
	if err != nil {
		t.Fatalf("Mnemonic() failed: %v", err)
	}
	words := strings.Fields(mnemonic)
	if len(words) != 25 {
		t.Errorf("Mnemonic should have 25 words, got %d", len(words))
	}

	// Recover key from mnemonic
	recoveredKey, lang, err := MnemonicToKey(mnemonic)
	if err != nil {
		t.Fatalf("MnemonicToKey() failed: %v", err)
	}
	if lang != "english" {
		t.Errorf("MnemonicToKey() language = %s, want english", lang)
	}

	if recoveredKey != key.PrivateSpendKey {
		t.Error("Roundtrip failed: recovered key doesn't match original")
	}
}

func TestNewKeyFromMnemonic(t *testing.T) {
	mnemonic := "skater fountain lair oars delayed lopped pause duckling lumber exit jingle until dolphin ought ramped makeup adept joking optical abrasive ability puddle popular rockets makeup"
	expectedAddress := "43FdbhX4svdi9cNXgKoei5HKQwGrBXdrm1ubqtxVeJJL48Srgt9Qefc93pvAeNk1ELK8oG46NSzHJ1XiYRgAjowNP7Yc6p4"

	key, err := NewKeyFromMnemonic(mnemonic, NetworkMainnet)
	if err != nil {
		t.Fatalf("NewKeyFromMnemonic() failed: %v", err)
	}

	if key.Address != expectedAddress {
		t.Errorf("Address = %s, want %s", key.Address, expectedAddress)
	}
}

func TestMnemonicInvalidLength(t *testing.T) {
	_, _, err := MnemonicToKey("one two three")
	if err != ErrInvalidMnemonicLength {
		t.Errorf("Expected ErrInvalidMnemonicLength, got %v", err)
	}
}

func TestMnemonicInvalidChecksum(t *testing.T) {
	// Valid mnemonic with wrong checksum word
	mnemonic := "skater fountain lair oars delayed lopped pause duckling lumber exit jingle until dolphin ought ramped makeup adept joking optical abrasive ability puddle popular rockets wrong"
	_, _, err := MnemonicToKey(mnemonic)
	if err != ErrInvalidChecksum {
		t.Errorf("Expected ErrInvalidChecksum, got %v", err)
	}
}

func TestMnemonicInvalidWord(t *testing.T) {
	// Mnemonic with invalid word
	mnemonic := "skater fountain lair oars delayed lopped pause duckling lumber exit jingle until dolphin ought ramped makeup adept joking optical abrasive ability puddle popular invalidword makeup"
	_, _, err := MnemonicToKey(mnemonic)
	if err != ErrWordNotFound {
		t.Errorf("Expected ErrWordNotFound, got %v", err)
	}
}

func TestMultiLanguageMnemonic(t *testing.T) {
	// Generate a new key
	key, err := NewKey(NetworkMainnet)
	if err != nil {
		t.Fatalf("Failed to generate key: %v", err)
	}

	// Test all available languages
	for langName := range Languages {
		t.Run(langName, func(t *testing.T) {
			// Convert key to mnemonic in this language
			mnemonic, err := key.Mnemonic(langName)
			if err != nil {
				t.Fatalf("Failed to convert key to mnemonic: %v", err)
			}

			// Recover key from mnemonic (with auto-detection)
			recovered, err := NewKeyFromMnemonic(mnemonic, NetworkMainnet)
			if err != nil {
				t.Fatalf("Failed to recover key from mnemonic: %v", err)
			}

			// Verify the recovered key matches
			if recovered.Address != key.Address {
				t.Errorf("Address mismatch: got %s, want %s", recovered.Address, key.Address)
			}
		})
	}
}

func TestUnknownLanguage(t *testing.T) {
	key, err := NewKey(NetworkMainnet)
	if err != nil {
		t.Fatalf("Failed to generate key: %v", err)
	}

	_, err = key.Mnemonic("klingon")
	if !errors.Is(err, ErrUnknownLanguage) {
		t.Errorf("Expected ErrUnknownLanguage, got %v", err)
	}
}

func TestAvailableLanguages(t *testing.T) {
	languages := AvailableLanguages()
	if len(languages) != len(Languages) {
		t.Errorf("Expected %d languages, got %d", len(Languages), len(languages))
	}

	// Check that all expected languages are present
	expected := []string{"english", "spanish", "japanese", "russian", "german", "french", "italian", "dutch", "portuguese", "esperanto", "lojban", "chinesesimplified", "englishold"}
	for _, exp := range expected {
		found := false
		for _, lang := range languages {
			if lang == exp {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("Expected language %s not found in available languages", exp)
		}
	}
}
