/*
 * MoneroPay is a Monero payment processor.
 * Copyright (C) 2026 Laurynas Četyrkinas <laurynas@digilol.net>
 *
 * MoneroPay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MoneroPay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MoneroPay.  If not, see <https://www.gnu.org/licenses/>.
 */

// Code generated by generate_wordlists.py. DO NOT EDIT.

package xmrkey

// Language represents a mnemonic language with its wordlist and configuration.
type Language struct {
	Name        string   // Native name of the language
	EnglishName string   // English name of the language
	PrefixLen   int      // Unique prefix length for checksum calculation
	Words       []string // The 1626 words in the wordlist
}

// Languages contains all available mnemonic languages.
var Languages = map[string]*Language{
	"chinesesimplified": {
		Name:        "简体中文 (中国)",
		EnglishName: "Chinese (simplified)",
		PrefixLen:   1,
		Words:       ChineseSimplifiedWordlist,
	},
	"dutch": {
		Name:        "Nederlands",
		EnglishName: "Dutch",
		PrefixLen:   4,
		Words:       DutchWordlist,
	},
	"english": {
		Name:        "English",
		EnglishName: "English",
		PrefixLen:   3,
		Words:       EnglishWordlist,
	},
	"englishold": {
		Name:        "EnglishOld",
		EnglishName: "English (old)",
		PrefixLen:   4,
		Words:       EnglishOldWordlist,
	},
	"esperanto": {
		Name:        "Esperanto",
		EnglishName: "Esperanto",
		PrefixLen:   4,
		Words:       EsperantoWordlist,
	},
	"french": {
		Name:        "Français",
		EnglishName: "French",
		PrefixLen:   4,
		Words:       FrenchWordlist,
	},
	"german": {
		Name:        "Deutsch",
		EnglishName: "German",
		PrefixLen:   4,
		Words:       GermanWordlist,
	},
	"italian": {
		Name:        "Italiano",
		EnglishName: "Italian",
		PrefixLen:   4,
		Words:       ItalianWordlist,
	},
	"japanese": {
		Name:        "日本語",
		EnglishName: "Japanese",
		PrefixLen:   3,
		Words:       JapaneseWordlist,
	},
	"lojban": {
		Name:        "Lojban",
		EnglishName: "Lojban",
		PrefixLen:   4,
		Words:       LojbanWordlist,
	},
	"portuguese": {
		Name:        "Português",
		EnglishName: "Portuguese",
		PrefixLen:   4,
		Words:       PortugueseWordlist,
	},
	"russian": {
		Name:        "русский язык",
		EnglishName: "Russian",
		PrefixLen:   4,
		Words:       RussianWordlist,
	},
	"spanish": {
		Name:        "Español",
		EnglishName: "Spanish",
		PrefixLen:   4,
		Words:       SpanishWordlist,
	},
}
